### ISSUE TITLE
Migrate Wordpress to Cloud.gov/Cloud Foundry

### ISSUE THREAD

**Issue by JJediny** [GSA/datagov-cloud-migration#10] opened 2016-01-04 16:20 UTC
While we are still moving forward with deploying CKAN using Docker. To get more familiar with Cloud Foundry we will migrate Wordpress separately

**Comment by philipashlock** [comment] 2016-01-07 19:17
Closing this as a duplicate of #7

**Closed by philipashlock** 2016-01-07 19:17 UTC
